version: "3.7"

networks:
  servicos:
    external:
      name: servicos

services:
  portainer:
    image: "portainer/portainer-ce:2.9.1"
    container_name: "portainer"
    restart: always
    #cria senha sensivel
    command: --admin-password='$$2y$$12$$G0u7sVYXDoCWYfBaPqwFOu00X.uHOXhGTF.mcySC2M1pxyWcXUOHe'
    networks:
      - servicos
    ports:
      - "9011:9000"
    volumes:
      - /opt/dados-docker/portainer/:/data
      - /var/run/docker.sock:/var/run/docker.sock
