---
# tasks file for common
- name: update SO
  apt:
    name: "*"
    update_cache: yes


- name: Check Dist Version
  shell: cat /etc/os-release
  register: response
- debug: msg="{{ response.stdout }}"


- name:  instalar pacotes no ubuntu handlers
  apt:
    name:
      - net-tools
      - telnet      
      - htop
      - wget
    state: latest




 


